# Generated by Django 6.0 on 2025-12-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
